### PR TITLE
0.0.4.1

### PR DESCRIPTION
**Pull request by swainn**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by swainn** [comment]
@snowman2 can you merge? I need a build for python 3.7 for gsshapy. The build for Python 2.7 wasn't working on windows, so I removed all Python 2.7 builds.

**Comment by swainn** [comment]
I agree to be a maintainer.

**Comment by snowman2** [comment]
Thanks Nathan. I bet the reason python 3 works is it removed pynio. Mind removing pynio from the list now since it is ignored and not required? Also, it should enable doing a noarch build.

**Comment by snowman2** [comment]
Trying it out now.

**Comment by snowman2** [comment]
@conda-forge-admin, please rerender.

**Comment by swainn** [comment]
@snowman2 thanks for merging! And noarch is even better!

**Comment by snowman2** [comment]
Thanks for the update :+1:

**Pull request merged**
